# Generated by Django 5.2.8 on 2025-11-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_emergencycontact_sosalert_favoritezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favoritezone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoritezone',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoritezone',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='zonevote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='zonevote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zonevote',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='FavoriteZone',
        ),
        migrations.DeleteModel(
            name='SOSAlert',
        ),
        migrations.DeleteModel(
            name='ZoneVote',
        ),
    ]
